version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:v6.9.1
    ports:
      - 8545:8545
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - -l
      - '8000038'
      - -i
      - '1234'
      - -e
      - '100000'
      - -a
      - '10'
      - -u
      - '0'
      - -g
      - '1000000000'
      - -m
      - 'wait nephew visual song prevent ribbon much stick hour token account food'
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
  ethboards-sc:
    environment:
      - WEB3_HOST=ganache
      - WEB3_PORT=8545
      - WEB3_NETWORK=local
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
    image: ethboards-statechannels:latest
    ports:
      - 8546:8546
    links:
      - "mongodb:mongodb"
      - "ganache:ganache"
 
