apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  clusterIP: 10.40.14.152
  ports:
      # service port in cluster
    - port: 27017
      # port to contact inside container
      targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP